// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentApp.Models;

#nullable disable

namespace StudentApp.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20250218023446_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentApp.Models.Program", b =>
                {
                    b.Property<string>("ProgramCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProgramCode");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            ProgramCode = "CPA",
                            ProgramName = "Computer Programmer Analyst"
                        },
                        new
                        {
                            ProgramCode = "BACS",
                            ProgramName = "Bachelor of Applied Computer Science"
                        });
                });

            modelBuilder.Entity("StudentApp.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GPA")
                        .HasColumnType("float");

                    b.Property<string>("Hobby")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProgramCode1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramCode");

                    b.HasIndex("ProgramCode1");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(737, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Goku",
                            GPA = 4.0,
                            Hobby = "Training, Eating",
                            LastName = "Son",
                            ProgramCode = "BACS"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(732, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Vegeta",
                            GPA = 3.8999999999999999,
                            Hobby = "Fighting, Training",
                            LastName = "Saiyan",
                            ProgramCode = "CPA"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(757, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gohan",
                            GPA = 3.7999999999999998,
                            Hobby = "Studying, Protecting Earth",
                            LastName = "Son",
                            ProgramCode = "BACS"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(766, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Trunks",
                            GPA = 3.7000000000000002,
                            Hobby = "Sword Fighting, Training",
                            LastName = "Brief",
                            ProgramCode = "BACS"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(732, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Piccolo",
                            GPA = 4.0,
                            Hobby = "Training, Meditation",
                            LastName = "Namekian",
                            ProgramCode = "CPA"
                        });
                });

            modelBuilder.Entity("StudentApp.Models.Student", b =>
                {
                    b.HasOne("StudentApp.Models.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentApp.Models.Program", null)
                        .WithMany("Students")
                        .HasForeignKey("ProgramCode1");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("StudentApp.Models.Program", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
